# Generated by Django 4.2.7 on 2024-01-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0002_order_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.CharField(max_length=100, unique=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_url",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
