# Generated by Django 4.2.7 on 2024-01-15 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0003_monosettings_order_invoice_id_order_invoice_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="invoice_id",
            new_name="order_id",
        ),
    ]
