# Generated by Django 4.2.7 on 2024-01-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0004_rename_invoice_id_order_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monosettings",
            name="public_key",
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
